### ISSUE TITLE
Rewrite class component to function component with hooks

### ISSUE THREAD

**Issue by draperunner** [draperunner/kramster#13]
The Questions container in `src/containers/Questions/index.jsx` is a class component. I'd like it to be a function component that uses React hooks instead of lifecycle methods and `this.state`.

**Comment by andersonmalheiro** [comment]
I will try this

**Comment by andersonmalheiro** [comment]
I've did it, but I can't manage to test the page. How can it be tested?

**Comment by draperunner** [comment]
Have you followed the instructions in README.md, including testing with the backend server?

**Comment by icancode007** [comment]
If not completed I can go for it
