### ISSUE TITLE
Inconsistent licensing

### ISSUE THREAD

**Issue by stianjensen** [draperunner/kramster#2]
Hey, cool project!

I checked out the license (https://github.com/draperunner/Kramster/blob/master/LICENSE.md) and saw that you've used a CC Share-alike license. Creative Commons recommends against using this license for software (Explained here: https://wiki.creativecommons.org/index.php/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F).

Also, in bower.json and package.json different licenses are specified. Not a big deal, and I guess they're auto-generated, but if you decide to update the licensing for the project, it would be nice if the correct license was reflected there as well.

**Comment by draperunner** [comment]
Hi! Thanks for pointing this out! I haven't payed too much attention to the license. You're right that the license fields in bower.json and package.json are auto-generated. I will find a license that suits my needs and update.
