### ISSUE TITLE
Alternatives have different widths

### ISSUE THREAD

**Issue by estensen** [draperunner/kramster#7]
Thanks for spending so much time creating Kramster! I have personally used it a lot prepping for finals.

I think the design would look more consistent if the alternatives had the same width. They are when the screen size is small enough, but not on a large screen.

<img width="1154" alt="screenshot 2018-11-29 13 02 42" src="https://user-images.githubusercontent.com/9142800/49220709-322b0b00-f3d7-11e8-8d6a-f5b6aed92af8.png">

**Comment by draperunner** [comment]
I see your point, but I don't know if that would look good for exams with short and few alternatives like True/False. And I'd rather not have conditional styling based on the size of the content.

I'll close this. but keep it in mind.

I am glad you like Kramster! 💯
