### ISSUE TITLE
Refused to load the font '<URL>' because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by estensen** [draperunner/kramster#8]
Feel free to close this if it's too niche.

I think it's because the CSP is too strict. For the record it works perfectly in incognito, so it might have [something to do with the Chrome extension Grammarly](https://stackoverflow.com/a/50672596)

<img width="795" alt="screenshot 2018-11-29 13 18 52" src="https://user-images.githubusercontent.com/9142800/49221411-54be2380-f3d9-11e8-9051-26a1b154beef.png">

**Comment by draperunner** [comment]
Hm, I don't see this. Can you verify if it is Grammarly or not?

**Comment by estensen** [comment]
Yes, after removing Grammarly from Chrome it disappears
